name: .NET CI

on:
  push:
    branches:
      - main
      - Member-1---Identity-&-Access
      - Member-2---Infrastructure
      - Member-3---Reservations
      - Member-4---QR-/-Maps-/-Integration
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/SmartSolarMicrogridAPI/SmartSolarMicrogridAPI.csproj

      - name: Build project
        run: dotnet build Backend/SmartSolarMicrogridAPI/SmartSolarMicrogridAPI.csproj --no-restore --configuration Release
